apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-bootstrap-script
data:
  init.sh: |
    #!/usr/bin/env bash
    echo "hack"

{{- if .Values.keycloak.enabled }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prism-agent-realm-import
data:
  prism-agent.json: |
    {
      "realm": "prism-agent",
      "enabled": true
    }

{{- end }}
